version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: TableMasterDataBase
    hostname: TableMaster
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Max2003?"
    entrypoint: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Max2003?' -C -Q 'CREATE DATABASE TableMaster;' && tail -f /dev/null"
    restart: always
    networks:
      - sqlserver-network

networks:
  sqlserver-network:
    driver: bridge
