-- Script d'initialisation PostgreSQL pour TableMaster.
-- DbUp execute ce script une seule fois et journalise son passage.

CREATE TABLE "User" (
    "Id"          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Email"       VARCHAR(320) NOT NULL,
    "Password"    VARCHAR(255) NOT NULL,
    "FirstName"   VARCHAR(100) NOT NULL,
    "LastName"    VARCHAR(100) NOT NULL,
    "AccountType" SMALLINT NOT NULL DEFAULT 0,
    "CreatedAt"   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_User_Email" UNIQUE ("Email")
);

CREATE TABLE "Restaurant" (
    "Id"                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"                    BIGINT NOT NULL,
    "RestaurantName"            VARCHAR(200) NOT NULL,
    "StreetNumber"              VARCHAR(10) NULL,
    "StreetName"                VARCHAR(200) NULL,
    "PostalCode"                VARCHAR(10) NULL,
    "City"                      VARCHAR(100) NULL,
    "Latitude"                  DECIMAL(9, 6) NULL,
    "Longitude"                 DECIMAL(9, 6) NULL,
    "Phone"                     VARCHAR(15) NULL,
    "CuisineType"               VARCHAR(100) NULL,
    "PaymentMethods"            VARCHAR(200) NULL,
    "Description"               TEXT NULL,
    "CreatedAt"                 TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "IsAutoValidateReservation" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Restaurant" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Restaurant_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id")
);

CREATE TABLE "UserRefreshTokens" (
    "Id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"     BIGINT NOT NULL,
    "TokenHash"  TEXT NOT NULL,
    "ExpiryDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "CreatedAt"  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DeviceInfo" VARCHAR(255) NULL,
    CONSTRAINT "PK_UserRefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserRefreshTokens_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TableEntity" (
    "Id"            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RestaurantId"  BIGINT NOT NULL,
    "TableNumber"   INT NOT NULL,
    "NumberOfSeats" INT NOT NULL,
    "CreatedAt"     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_TableEntity" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TableEntity_Restaurant" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurant" ("Id")
);

CREATE TABLE "Menu" (
    "Id"           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RestaurantId" BIGINT NOT NULL,
    "Category"     VARCHAR(100) NOT NULL,
    "ItemName"     VARCHAR(200) NOT NULL,
    "Description"  TEXT NULL,
    "Price"        DECIMAL(10, 2) NOT NULL,
    "CreatedAt"    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_Menu" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Menu_Restaurant" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurant" ("Id")
);

CREATE TABLE "DailyActivity" (
    "Id"           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RestaurantId" BIGINT NOT NULL,
    "DayOfWeek"    SMALLINT NOT NULL,
    "StartTime"    TIME NOT NULL,
    "EndTime"      TIME NOT NULL,
    "CreatedAt"    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_DailyActivity" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DailyActivity_Restaurant" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurant" ("Id")
);

CREATE TABLE "ClosedDayException" (
    "Id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RestaurantId"       BIGINT NOT NULL,
    "ExceptionDateBegin" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "ExceptionDateEnd"   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "Reason"             VARCHAR(255) NULL,
    "CreatedAt"          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_ClosedDayException" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ClosedDayException_Restaurant" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurant" ("Id")
);

CREATE TABLE "Reservation" (
    "Id"              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"          BIGINT NOT NULL,
    "TableId"         BIGINT NOT NULL,
    "RestaurantId"    BIGINT NOT NULL,
    "ReservationDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "NumberOfPeople"  INT NOT NULL,
    "SpecialRequest"  VARCHAR(500) NULL,
    "CreatedAt"       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "IsValidate"      BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Reservation" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reservation_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id"),
    CONSTRAINT "FK_Reservation_Table" FOREIGN KEY ("TableId") REFERENCES "TableEntity" ("Id"),
    CONSTRAINT "FK_Reservation_Restaurant" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurant" ("Id")
);

CREATE TABLE "Review" (
    "Id"           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"       BIGINT NOT NULL,
    "RestaurantId" BIGINT NOT NULL,
    "Rating"       SMALLINT NOT NULL,
    "Comment"      TEXT NULL,
    "CreatedAt"    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_Review" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Review_Restaurant" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurant" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Review_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_Review_User_Restaurant" UNIQUE ("UserId", "RestaurantId"),
    CONSTRAINT "CK_Review_Rating" CHECK ("Rating" >= 1 AND "Rating" <= 5)
);

CREATE OR REPLACE FUNCTION delete_old_closed_day_exceptions()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM "ClosedDayException"
    WHERE "ExceptionDateEnd" < CURRENT_TIMESTAMP;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "DeleteOldClosedDayExceptions"
AFTER INSERT OR UPDATE ON "ClosedDayException"
FOR EACH STATEMENT
EXECUTE FUNCTION delete_old_closed_day_exceptions();
