CREATE TABLE "UserDeviceTokens" (
    "Id"             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"         BIGINT NOT NULL,
    "DeviceToken"    VARCHAR(500) NOT NULL,
    "DevicePlatform" VARCHAR(50) NULL,
    "LastSeenAt"     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_UserDeviceTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserDeviceTokens_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "UQ_UserDeviceTokens_User_DeviceToken"
ON "UserDeviceTokens" ("UserId", "DeviceToken");
