-- Ajoute les salles de restaurant et le placement spatial des tables.

CREATE TABLE IF NOT EXISTS "RestaurantRoom" (
    "Id"                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RestaurantId"       BIGINT NOT NULL,
    "Name"               VARCHAR(120) NOT NULL,
    "SortOrder"          INT NOT NULL DEFAULT 0,
    "BoundaryPointsJson" JSONB NOT NULL DEFAULT '[{"x":0.05,"y":0.05},{"x":0.95,"y":0.05},{"x":0.95,"y":0.95},{"x":0.05,"y":0.95}]'::jsonb,
    "CreatedAt"          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_RestaurantRoom" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RestaurantRoom_Restaurant" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurant" ("Id") ON DELETE CASCADE
);

ALTER TABLE "TableEntity"
    ADD COLUMN IF NOT EXISTS "RoomId" BIGINT NULL,
    ADD COLUMN IF NOT EXISTS "Shape" SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS "PositionX" NUMERIC(6, 4) NOT NULL DEFAULT 0.1,
    ADD COLUMN IF NOT EXISTS "PositionY" NUMERIC(6, 4) NOT NULL DEFAULT 0.1,
    ADD COLUMN IF NOT EXISTS "Width" NUMERIC(6, 4) NOT NULL DEFAULT 0.16,
    ADD COLUMN IF NOT EXISTS "Height" NUMERIC(6, 4) NOT NULL DEFAULT 0.12,
    ADD COLUMN IF NOT EXISTS "RotationDegrees" NUMERIC(6, 2) NOT NULL DEFAULT 0;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_TableEntity_RestaurantRoom'
    ) THEN
        ALTER TABLE "TableEntity"
            ADD CONSTRAINT "FK_TableEntity_RestaurantRoom"
            FOREIGN KEY ("RoomId") REFERENCES "RestaurantRoom" ("Id") ON DELETE RESTRICT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'CK_TableEntity_Shape'
    ) THEN
        ALTER TABLE "TableEntity"
            ADD CONSTRAINT "CK_TableEntity_Shape"
            CHECK ("Shape" IN (0, 1, 2));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'CK_TableEntity_NormalizedPosition'
    ) THEN
        ALTER TABLE "TableEntity"
            ADD CONSTRAINT "CK_TableEntity_NormalizedPosition"
            CHECK (
                "PositionX" >= 0 AND "PositionX" <= 1 AND
                "PositionY" >= 0 AND "PositionY" <= 1 AND
                "Width" > 0 AND "Width" <= 1 AND
                "Height" > 0 AND "Height" <= 1
            );
    END IF;
END $$;

INSERT INTO "RestaurantRoom" ("RestaurantId", "Name", "SortOrder", "BoundaryPointsJson")
SELECT R."Id",
       'Salle principale',
       0,
       '[{"x":0.05,"y":0.05},{"x":0.95,"y":0.05},{"x":0.95,"y":0.95},{"x":0.05,"y":0.95}]'::jsonb
FROM "Restaurant" R
WHERE NOT EXISTS (
    SELECT 1
    FROM "RestaurantRoom" RR
    WHERE RR."RestaurantId" = R."Id"
);

UPDATE "TableEntity" T
SET "RoomId" = RR."Id"
FROM "RestaurantRoom" RR
WHERE T."RoomId" IS NULL
  AND RR."RestaurantId" = T."RestaurantId"
  AND RR."Id" = (
      SELECT RR2."Id"
      FROM "RestaurantRoom" RR2
      WHERE RR2."RestaurantId" = T."RestaurantId"
      ORDER BY RR2."SortOrder", RR2."Id"
      LIMIT 1
  );

WITH numbered AS (
    SELECT "Id",
           ROW_NUMBER() OVER (PARTITION BY "RestaurantId" ORDER BY "TableNumber", "Id") - 1 AS rn
    FROM "TableEntity"
)
UPDATE "TableEntity" T
SET "PositionX" = 0.10 + ((numbered.rn % 5) * 0.17),
    "PositionY" = 0.12 + ((numbered.rn / 5) * 0.16),
    "Width" = CASE WHEN T."NumberOfSeats" <= 2 THEN 0.12 ELSE 0.16 END,
    "Height" = CASE WHEN T."NumberOfSeats" <= 2 THEN 0.12 ELSE 0.14 END,
    "Shape" = CASE WHEN T."NumberOfSeats" <= 2 THEN 0 ELSE 1 END
FROM numbered
WHERE numbered."Id" = T."Id";

CREATE INDEX IF NOT EXISTS "IX_RestaurantRoom_RestaurantId"
    ON "RestaurantRoom" ("RestaurantId");

CREATE INDEX IF NOT EXISTS "IX_TableEntity_RoomId"
    ON "TableEntity" ("RoomId");
