CREATE TABLE IF NOT EXISTS "UserPasswordResetTokens" (
    "Id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "UserId"     BIGINT NOT NULL,
    "TokenHash"  TEXT NOT NULL,
    "ExpiryDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "CreatedAt"  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UsedAt"     TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT "PK_UserPasswordResetTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserPasswordResetTokens_User" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserPasswordResetTokens_TokenHash"
    ON "UserPasswordResetTokens" ("TokenHash");

CREATE INDEX IF NOT EXISTS "IX_UserPasswordResetTokens_UserId"
    ON "UserPasswordResetTokens" ("UserId");
