version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: TableMasterDataBase
    hostname: TableMaster
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Max2003?"
    volumes:
      - ./sql-scripts:/sql-scripts  # Monte le dossier contenant ton fichier .sql
    entrypoint: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Max2003?' -C -i /sql-scripts/init-db.sql && tail -f /dev/null"
    restart: always
    networks:
      - sqlserver-network

  api:
    image: table_master_api:latest
    container_name: TableMasterApi
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=TableMaster;Database=TableMaster;User Id=sa;Password=Max2003?;Encrypt=False;TrustServerCertificate=False;
    ports:
      - "8080:8080"
    restart: always
    networks:
      - sqlserver-network

networks:
  sqlserver-network:
    driver: bridge
